version: '3'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
