version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - '3307:3306'
    restart: always
  app:
    build: 
      context: .
      dockerfile: dockerfile
      target: run
    image: nestjs-boilerplate:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV: production
    restart: unless-stopped